version: "3"

services:
  crypto_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - crypto_network

  crypto_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@rails.com"
      PGADMIN_DEFAULT_PASSWORD: "425639"
    ports:
      - "8080:80"
    depends_on:
      - crypto_db
    networks:
      - crypto_network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - crypto_db
    networks:
      - crypto_network
  
networks:
  crypto_network:
    driver: bridge